### ISSUE TITLE
Changes required for VisUI 1.0.0

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-lml-vis#7]
- [x] Moved `InputValidator`
- [x] Refactored `FileChooserListener`
- [x] `SeparatorStyle.vertical` removed
- [x] `Tooltip` constructors deprecated, use `Tooltip.Builder`
- [x] `VerticalFlowGroup`
  - [x] `spacing`
- [x] `HorizontalFlowGroup`
  - [x] `spacing`
- [x] Update to libGDX 1.9.2
- [x] ~~`ButtonBar` support~~
- [x] `ListView`
  - [x] Footer and header support (?).
  - [x] Custom list adapter.

**Comment by czyzby** [comment]
Will `Tooltip` constructors be removed? Using a constructor will most likely limit the creation of unnecessary objects (builders), and this is a private API anyway, so I don't expect anyone will complain about readability.

**Comment by kotcrab** [comment]
I intended to remove them all but you are right about creating unnecessary objects so I will leave the most basic ones (those taking tooltip style).

**Comment by czyzby** [comment]
I don't think `ButtonBar` will be supported by `gdx-lml-vis`. As I've previously said in case of dialog utilities, `gdx-lml` already allows to quickly construct dialogs (or button groups, for that matter). Since `ButtonBar` creates its own table, all size, padding, spacing (etc.) attributes would be lost. It seems to affect only the order of buttons, without adding new functionalities - existing layout widgets are much more flexible and less editor-oriented; actually, buttons in the same places on every platform would give a more seamless experience when changing OS-es, especially in case of games. (And yes, it would require some extra work, since `ButtonBar` is not an `Actor` itself.)

**Comment by czyzby** [comment]
`gdx-lml-vis 1.5.1.9.2` will be released after GWT fix in VisUI.
